//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoom
    {
        public int Id { get; set; }
        public string RoomNo { get; set; }
        public string RoomName { get; set; }
        public string RoomType { get; set; }
    }
}
