//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string LoginName { get; set; }
        public string Email { get; set; }
        public string LoginHash { get; set; }
        public Nullable<int> IsAdmin { get; set; }
    }
}
